title: ITEgraph
email: 
description: >- 
    A Graph Model of the TLS Ecosystem and its Internet-wide Application
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://imc2023-98.github.io"
github_username: 

#remote_theme: pages-themes/minimal@v0.2.0

theme: minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
